/* eslint-disable @typescript-eslint/no-require-imports */

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@shadcn/ui/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        headerBg: 'var(--header-bg-gradient)',
        sidebarActiveTab: 'var(--sidebar-active-tab)',
        sidebarGetCoinsBg: 'var(--sidebar-get-coins-bg)',
        sidebarHomeBg: 'var(--sidebar-home-bg)',
        sidebarDropdownBg: 'var(--sidebar-dropdown-bg)',
        sidebarPromoBg: 'var(--sidebar-promo-bg)',
        sidebarImageBg: 'var(--sidebar-image-bg)',
        sidebarHoverBg: 'var(--sidebar-hover-bg)',
        authBg: 'var(--auth-bg)',
        formBg: 'var(--form-bg)',
        authBtnBg: 'var(--auth-btn-bg)',
        skillzLoginBg: 'var(--skillz-login-bg)',
        skillzLoginBorder: 'var(--skillz-login-border)',
        experienceBarBg: 'var(--experience-bar-bg)',
        coinToggleBorder: 'var(--coin-toggle-border)',
        scCoinToggleBorderImageSource: 'var(--sc-coin-toggle-border-image-source)',
        gcCoinToggleBorderImageSource: 'var(--gc-coin-toggle-border-image-source)',
        gcCoinToggleBg: 'var(--gc-coin-toggle-bg)',
        scCoinToggleBg: 'var(--sc-coin-toggle-bg)',
        headerDropdownBg: 'var(--header-dropdown-bg)',
        navMobileBg: 'var(--nav-Mobile-bg)',
        storeCircleBg: 'var(--store-circle-bg)',
        headerDropdownBorder: 'var(--header-dropdown-border)',
        dropdownContentBg: 'var(--header-dropdown-content)',
        storeSubmitButton: 'var(--store-submit-button)',
        storeSubmitBorder: 'var(--store-submit-border)',
        packageCardBg: 'var(--package-card-bg)',
        idPackageBg: 'var(--id-card-bg)',
        packageBuyBtnBorder: 'var(--package-buy-btn-border)',
        limitedTimeBg: 'var(--limited-time-bg)',
        limitedTimeBgMobile: 'var(--limited-time-bg-mobile)',
        featuredBg: 'var(--featured-bg)',
        specialPackageBg: 'var(--special-package-bg)',
        specialPakageBorder: 'var(--special-package-border)',
        promoDialogBorder: 'var(--promo-dialog-border)',
        goldPackageTabBorder: 'var(--gold-package-tab-border)',
        profileTabBg: 'var(--profile-tab-bg)',
        activeProfileTabBg: 'var(--active-profile-tab-bg)',
        profileTabBorder: 'var(--profile-tab-border)',
        activeProfileTabBorder: 'var(--active-profile-tab-border)',
        profileBtn: 'var(--profile-btn)',
        transactionsHeaderBg: 'var(--transaction-table-header-bg)',
        layoutGradient: 'var(--layout-gradient)',
        transactonRowBg: 'var(--transaction-table-row-bg)',
        vipTreasureChest: 'var(--vip-treasure-chest)',
        transactionLine: 'var(--transaction-line)',
        paymentInputBorder: 'var(--payment-input-border)',
        streakPopupCTA: 'var(--streak-popup-cta)',
        streakPopupCTADisabled: 'var(--streak-popup-cta-disabled)',
        promotionCardBorder: 'var(--promotion-card-border)',
        howItWorksBg: 'var(--vip-howItWorks-bg)',
        howItWorksBorder: 'var(--vip-howItWorks-border)',
        vipBackground: 'var(--vipBackground)',
        vipCardActiveBorder: 'var(--vipCardActiveBorder)',
        vipActiveBg: 'var(--vipActiveBg)',
        'vip-claim': 'var(--vip-claim-bg)',
        'vip-locked': 'var(--vip-locked-bg)',
        'quartz-card': 'var(--quartz-card-bg)',
        'sapphite-card': 'var(--sapphite-card-bg)',
        'emerald-card': 'var(--emerald-card-bg)',
        'pearl-card': 'var(--pearl-card-bg)',
        'ruby-card': 'var(--ruby-card-bg)',
        'obsidian-card': 'var(--obsidian-card-bg)',
        'quartz-card-sub-box': 'var(--quartz-card-sub-box)',
        'sapphire-card-sub-box': 'var(--sapphire-card-sub-box)',
        'emerald-card-sub-box': 'var(--emerald-card-sub-box)',
        'ruby-card-sub-box': 'var(--ruby-card-sub-box)',
        'treasure-chest-bg': 'var(--treasure-chest-bg)',
        'progress-bar': 'var(--progress-bar-color)',
        'button-gray-background':
          'linear-gradient(98.51deg, #FFFFFF -92.7%, rgba(255, 255, 255, 0.05) 23.72%, rgba(255, 255, 255, 0.09) 68.89%, rgba(255, 255, 255, 0.07) 100%)',
        'button-bg': 'linear-gradient(90deg, #002768 0%, #BE0B31 100%);',
        'button-green-background': 'linear-gradient(179.21deg, #0FA40D 0.61%, #006300 83.91%)',
        'vip-background':
          'radial-gradient(128.27% 437.03% at 93.88% -18.38%, rgba(11, 24, 54, 0.5) 0%, rgba(2, 17, 53, 0.5) 29.74%, rgba(13, 30, 68, 0.5) 50.97%, rgba(1, 14, 44, 0.5) 100%)',
        'progress-bar-inducator': 'linear-gradient(180deg, #EA9000 0%, #C16201 100%)',
        'buy-blue-background': ' linear-gradient(180deg, #006FFD 0%, #004297 100%)',
        'select-button-background':
          'linear-gradient(180deg, rgba(234, 144, 0, 0) 0%, rgba(234, 144, 0, 0.5) 100%)',
        'vip-capsule-background': 'linear-gradient(180deg, #041D57 0%, #21213B 100%)',
        'border-gradient': 'linear-gradient(180deg, #52a862 0%, #815e0e 100%)',
        'vip-button-background': 'linear-gradient(180deg, #161F45 0%, #1F203D 100%)',
        'custom-popover-gradient':
          'linear-gradient(180deg, #1B2846 0%, #061D54 42.08%, #0B1836 100%)',
        'blue-gradient': 'linear-gradient(97.58deg, #051D55 -70.97%, #030F2D 206.59%)',

        'tab-gradient': 'linear-gradient(180deg, var(--tab-bg-1) 0%, var(--tab-bg-2) 100%)',
        'view-all': ' linear-gradient(90deg, #831442 0%, #D16B22 100%);',
        'card-border': 'radial-gradient(97.32% 97.32% at 47.42% 2.68%, #BE0B31 0%, #D2901A 100%);',
        'collapsible-bg': 'linear-gradient(180deg, #5F0518 39.26%, #000A1C 100%);',
        'collapsable-dark': 'linear-gradient(180deg, #FFFFFF  39.26%, ##1E3A8A 100%);',
        sidebarbg: 'linear-gradient(177.73deg, rgba(64, 24, 195, 0.5) -39.8%, #071224 48.43%);',
        'redeem-box-bg': 'linear-gradient(90deg, #A436D0 0%, #3C7088 50%, #A436D0 100%)',
        'vip-box-bg': 'linear-gradient(126.3deg, #002768 6.74%, #550518 58.1%, #D2901A 140.13%);',
        'mobile-nav-bg': 'linear-gradient(90deg, #3B0617 0%, #140817 100%);',
        'cointoggler-bg': 'linear-gradient(90deg, #FFD700 -10%, #FFC107 40%, #FFEB3B 110%);',
        'cointoggler-green-bg':
          'linear-gradient(89.86deg, #2E8B57 -23.94%, #228B22 48.97%, #ADFF2F 120.83%);',
        'gc-bg': 'linear-gradient(90deg, #D2901A 0%, #983B34 100%);',
        'sc-bg': 'linear-gradient(90deg, #1FA657 0%, #D2901A 100%);',
        'dark-footer': 'linear-gradient(180deg, #1651AB 0%, #0041A5 100%)',
        'storeboxdark-bg':
          'radial-gradient(101.43% 101.43% at 50% 9.05%, #C0D8FF 0%, #FFFFFF 30.27%, #639DFF 100%);',
        vipdarkbox:
          'radial-gradient(116.23% 116.23% at 31.09% -16.23%, #FFFFFF 0%, #DDEAFF 35.52%, rgba(232, 208, 103, 0.33) 53.24%, #FF6787 78.36%, #FFC3D0 100%);',
        'setting-bg':
          'linear-gradient(185.03deg, #070919 21.57%, #251C1E 61.16%, #23030C 74.62%, #070815 109.03%);',
        'storecoin-bg': 'linear-gradient(90deg, #C5881C 0.48%, #FEE105 95.19%);',
        'buycoin-bg': 'radial-gradient(50% 50% at 50% 50%, #BA750F 0%, #E09F1F 100%);',
        'bonus-button-bg':
          'linear-gradient(96.71deg, #5F0518 -55.93%, #002768 -13.58%, #BE0B31 40.37%, #D9981C 117.56%);',
        'light-profile-bg': 'linear-gradient(90deg, #7da3e6 0%, #f37a88 100%);',
        sidebluewhite: 'linear-gradient(90deg, #FDFDFD 100%, #FFF2F2 0%);',
        'tab-light-theme': 'linear-gradient(180deg, #002768 0%, #004DCE 100%);',
        'main-lenior-gradient': ' linear-gradient(90deg, #FDFDFD 0%, #FFF2F2 100%);',
        'table-bg-gradient':
          ' conic-gradient(from 180deg at 50% 50%, #5F0518 0deg, #002768 172.63deg, #BE0B31 360deg)',
        'black-line': '#000',
        'login-btn-bg': 'var(--login-btn-gradient)',
        'AMOE-accordian-border': 'var(--AMOE-accordian-border)',
        'winner-blue': 'linear-gradient(90deg, #3853fe 0%, #071224 95.26%)',
        'winner-indigo': 'linear-gradient(90deg, #3956FD 0%, #071224 100%)',
        'winner-crimson': 'linear-gradient(90deg, #d82f4c 0%, #071224 100%)',
        'winner-fuchsia': 'linear-gradient(90deg, #b30ad0 0%, #170317 100%)',
        'winner-purple': 'linear-gradient(90deg, #933AFF 0%, #071224 100%)',
        'winner-violet': 'linear-gradient(90deg, #521EEA 0%, #071224 100%)',
        'mobileTable-footer-bg': 'var(--mobileTable-footer-bg)',
        vipPerksColor: 'var(--vipPerksColor)',
        activeTierBg: 'var(--activeTierBg)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['var(--font-inter)'],
        futura: ['var(--font-area-normal)'],
        roboto: ['var(--font-area-normal)'],
        cinzel: ['var(--font-area-normal)'],
        montserrat: ['var(--font-area-normal)'],
        khand: ['var(--font-area-normal)'],
        lexend: ['var(--font-area-normal)'],
        outfit: ['var(--font-area-normal)'],
        dmSans: ['var(--font-area-normal)'],
        carter: ['var(--font-area-normal)'],
        bebasNeue: ['var(--font-bebas-neue)'],
        geist: ['var(--font-geist)'],
        poppins: ['var(--font-poppins)'],
      },
      screens: {
        xts: '390px',
        xs: '440px',
        sm: '533px',
        md: '768px',
        lg: '1024px',
        xl: '1279px',
        xxl: '1450px',
      },
      transitionProperty: {
        height: 'height',
        opacity: 'opacity',
      },
      colors: {
        storeInputBg: 'var(--store-input-bg)',
        transactonRowBg2: 'var(--transaction-table-row-bg2)',
        storeInputBorder: 'var(--store-input-border)',
        storePromoBlockBg: 'var(--store-promo-block-bg)',
        packageCardBorder: 'var(--package-card-border)',
        idPackageBorder: 'var(--id-card-border)',
        bonusBg: 'var(--bonus-background)',
        bonusTextcolor: 'var(--bonus-text-color)',
        scBonusBg: 'var(--sc-bonus-bg)',
        scBonusText: 'var(--sc-bonus-text)',
        promoDialogBg: 'var(--promo-dialog-color)',
        goldPackageTabBG: 'var(--gold-package-tab-bg)',
        promoDialogError: 'var(--error-message-promoDialog)',
        promoInputBorder: 'var(--promo-input-border)',
        profileFormBg: 'var(--profile-form-input-bg)',
        dropdownBorder: 'var(--dropdown-border)',
        storeCircleBorder: ' var( --store-circle-border)',
        reedemBoxBg: 'var(--redeem-box-bg)',
        transactionText: 'var(--transaction-text)',
        stepBg: 'var(--step-container-bg)',
        paymentMethodBg: 'var(--payment-method-bg)',
        addNewCardBg: 'var(--add-new-card-bg}',
        paymentInputBg: 'var(--payment-input-bg)',
        scText: 'var(--sc-text)',
        verifyTabBg: 'var(--verify-tab-bg)',
        streakPopHeading: 'var(--streak-pop-heading)',
        amoeCta: 'var(--amoe-cta)',
        quartz: 'var(--quartz-color)',
        sapphire: 'var(--sapphire-color)',
        emerald: 'var(--emerald-color)',
        pearl: 'var(--pearl-color)',
        ruby: 'var(--ruby-color)',
        obsidian: 'var(--obsidian-color)',
        dailyRewardsHeader: 'var(--daily-missions-card-header)',
        'vip-dividing-line-bg': 'var(--vip-dividing-line)',
        'sapphire-text': 'var(--sapphire-text)',
        'emerald-text': 'var(--emerald-text)',
        'pearl-text': 'var(--pearl-text)',
        'ruby-text': 'var(--ruby-text)',
        'obsidian-text': 'var(--obsidian-text)',
        'vip-active': 'var(--vip-active-bg)',
        'quartz-card-border': 'var(--quartz-card-border)',
        'sapphire-card-border': 'var(--sapphire-card-border)',
        'emerald-card-border': 'var(--emerald-card-border)',
        'pearl-card-border': 'var(--pearl-card-border)',
        'ruby-card-border': 'var(--ruby-card-border)',
        'obsidian-card-border': 'var(--obsidian-card-border)',
        'pearl-card-sub-box': 'var(--pearl-card-sub-box)',
        'obsidian-card-sub-box': 'var(--obsidian-card-sub-box)',
        'kyc-verified-text': 'var(--kyc-verified-text)',
        'quartz-desktop': 'var(--quartz-desktop)',
        'sapphire-desktop': 'var(--sapphire-desktop)',
        'emerald-desktop': 'var(--emerald-desktop)',
        'pearl-desktop': 'var(--pearl-desktop)',
        'ruby-desktop': 'var(--ruby-desktop)',
        'obsidian-desktop': 'var(--obsidian-desktop)',
        quartzTextColor: 'var(--quartz-text-color)',
        sapphireTextColor: 'var(--sapphire-text-color)',
        emeraldTextColor: 'var(--emerald-text-color)',
        pearlTextColor: 'var(--pearl-text-color)',
        rubyTextColor: 'var(--ruby-text-color)',
        obsidiantextColor: 'var(--obsidian-text-color)',
        purchaseLimitInputBorder: 'var(--purchase-limit-input-border)',
        mobileTable: 'var(--mobileTable-bg)',
        vipPerksBorder: 'var(--vipPerksBorder)',
        coinToggleBg: {
          DEFAULT: 'var(--coin-toggle-bg)',
        },
        profileText: {
          DEFAULT: 'var(--profile-text)',
        },
        cardHoverBorder: {
          DEFAULT: 'var(--card-hover-border)',
        },
        authTabBg: {
          DEFAULT: 'var(--auth-tab-bg)',
        },
        authTabActiveBg: {
          DEFAULT: 'var(--auth-tab-active-bg)',
        },
        googleLoginText: {
          DEFAULT: 'var(--google-login-text)',
        },
        formInputBg: {
          DEFAULT: 'var(--form-input-bg)',
        },
        formInputBorder: {
          DEFAULT: 'var(--form-input-border)',
        },
        formInputText: {
          DEFAULT: 'var(--form-input-text)',
        },
        formInputPlaceholder: {
          DEFAULT: 'var(--form-input-placeholder)',
        },
        sidebarActiveTabBorder: {
          DEFAULT: 'var(--sidebar-active-tab-border)',
        },
        'sidebar-spin-wheel-button-border': {
          DEFAULT: 'var(--sidebar-spin-wheel-button-border)',
        },
        core: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary)',
        },
        goldCoin: {
          DEFAULT: 'var(--coin-gold)',
          foreground: 'var(--coin-gold)',
        },
        lightGreen: {
          DEFAULT: 'var(--light-green)',
        },
        aside: {
          DEFAULT: 'var(--sidebar-bg)',
        },
        headerBg: {
          DEFAULT: 'var(--header-bg-gradient)',
          start: 'var(--header-bg-gradient-start)',
          end: 'var(--header-bg-gradient-end)',
        },
        main: {
          DEFAULT: 'var(--main-background)',
        },
        btnSecondry: {
          DEFAULT: 'var(--btn-secondry)',
        },
        background: 'var(--main-background)',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'hsl(var(--primary-foreground))',
        },
        footer: {
          DEFAULT: 'var(--footer)',
          bgStart: 'var(--footer-bg-start)',
          bgEnd: 'var(--footer-bg-end)',
          text: 'var(--footer-text)',
          border: 'var(--footer-border-color)',
        },
        brand: {
          pink: 'var(--brand-pink)',
        },
        primaryLight: {
          DEFAULT: 'var(--primary-light)',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        'register-btn-border': 'var(--register-btn-border)',
        quartzBg: 'var(--quartz-bg)',
        levelColor: 'var(--level-color)',
        headerDropdownContentBorder: 'var(--header-dropdown-content-border)',
        textMute: 'var(--text-mute)',
        warning: 'var(--status-warning)',
        success: 'var(--status-success)',
        error: 'var(--status-error)',
        'accent-yellow': 'var(--color-accent-yellow)',
        'accent-green': 'var(--color-accent-green)',
        'accent-blue': 'var(--color-accent-blue)',
        'background-dark': 'var(--color-background-dark)',
        'secondary-light': 'var(--color-secondary-light)',
        'vibrant-purple': 'var(--color-vibrant-purple)',
        'primary-dark': 'var(--color-primary-dark)',
        violet: 'var(--color-violet)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'auth-btn-shadow': '0px 0px 10px 0px #FFFFFF33 inset',
        'cta-bottom-shadow': '0px 4px 10px 0px #00000066',
        'custom-auth': '0px 4px 19px 6px #BE0B316B',
        'buy-shadow': '0px 4px 13px 0px #BE0B316B',
        'toggle-shadow': '0px -2px 15px 0px #E79809C7;',
        'toggle-green-shadow': '0px -2px 15px 0px #9EFF9EC7',
        // 'search-shadow':'0px 4px 13px 0px linear-gradient(180deg, #5F0518 39.26%, #000A1C 100%);'
        'search-shadow': '0px 4px 21px #000A1C, 0px 8px 31px #5F0518',
        'store-card-shadow': 'inset 0px 0px 8px rgba(255, 255, 255, 0.2);',
        'inner-blue': 'inset 0px 4px 30px 10px rgba(100, 149, 237, 0.5);',
        'game-number': '0px 8.57px 10.28px rgba(244, 220, 3, 0.25)',
        cardHoverShadow: '0px 0px 8px 0px #ffffff40 inset',
        paymentInputShadow: '0px 0px 10px 0px #031621 inset',
        storeCircleShadow: '0px 0px 15px 0px #00000040',
        transactionsHeaderShadow: '0px 4px 44px 0px #000000F2',
        vipProgressSidebarShadow: 'var(--vip-progress-sidebar-shadow)',
        amoeCtaShadow: 'var(--amoe-cta-shadow)',
        purchaseLimitInputShadow: 'var(--purchase-limit-input-shadow)',
        amoeAccordianShadoe: '0px 0px 10px 0px #031621 inset',
        verifyphoneshadow: '0px 0px 10px 0px #031621 inset',
        vipTierBoxShadow: '0px 4px 4px 0px #3A3A3A40 inset',
        VipPerksShadow: ' 0px 4px 44px 0px #000000F2',
      },
      keyframes: {
        'collapsible-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        'collapsible-up': {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
        'scale-pulse': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        'winning-strip-scroll': {
          from: { transform: 'translate3d(0, 0, 0)' },
          to: { transform: 'translate3d(-50%, 0, 0)' },
        },
      },
      animation: {
        'collapsible-down': 'collapsible-down 300ms ease-out',
        'collapsible-up': 'collapsible-up 300ms ease-out',
        'scale-pulse': 'scale-pulse 1s ease-in-out infinite',
        'winning-strip-scroll': 'winning-strip-scroll 29s linear infinite',
      },
    },
  },
  safelist: [
    'div[data-radix-popper-content-wrapper]',
    'div[data-radix-select-content]',
    'div[data-radix-dialog-content]',
  ],
  // plugins: [require('tailwindcss-animate')],
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
    function ({ addUtilities }) {
      addUtilities({
        '.gradient-border': {
          border: '1px solid',
          borderImageSource: 'linear-gradient(90deg, #831442 0%, #D16B22 100%)',
          borderImageSlice: '1',
          borderRadius: '0.75rem',
        },
      });
    },
  ],
};
